AWSTemplateFormatVersion: 2010-09-09
Description: |
  Cloudformation Template for kittens carousel static website deploy on s3 through cloudfront and route 53
Parameters:
  HostedZoneName:
    Description: DNS Name of existing Amazon Route 53 hosted zone. exp. clarusway.us
    Type: AWS::Route53::HostedZone::Id

  KittensSubDomainName:
    Description: Full domain name for the App. ex. kittens.clarusway.us
    Type: String
    AllowedPattern: (?!-)[a-zA-Z0-9-.]{1,63}(?<!-)

Resources:
  MyBucket:
    Type: "AWS::S3::Bucket"
    Properties:
      AccessControl: PublicRead
      BucketName: !Ref KittensSubDomainName
      WebsiteConfiguration:
        IndexDocument: index.html
 
  MyBucketPolicy:
    Type: AWS::S3::BucketPolicy
    Properties:
      Bucket: !Ref MyBucket 
      PolicyDocument: 
        Statement: 
          - Sid: PublicReadGetObject
            Effect: Allow
            Principal: '*'
            Action: s3:GetObject
            Resource: !Join ['', ['arn:aws:s3:::', !Ref 'MyBucket', /*]]

  MyCertificate:
    Type: "AWS::CertificateManager::Certificate"
    Properties:
      CertificateTransparencyLoggingPreference: ENABLED 
      DomainName: !Ref KittensSubDomainName
      DomainValidationOptions:
        - DomainName: !Ref KittensSubDomainName
          HostedZoneId: !Ref HostedZoneName
      ValidationMethod: DNS 
  
  MyCloudfront:
    Type: "AWS::CloudFront::Distribution" 
    Properties:
      DistributionConfig:
        Aliases:
        - !Ref KittensSubDomainName
        Comment: Cloudfront Distribution pointing to Kittens S3 bucket
        DefaultCacheBehavior:
          AllowedMethods:  
          - GET
          - HEAD
          Compress: true
          ForwardedValues: 
            QueryString: true 
            Cookies:
              Forward: none 
          TargetOriginId: KittensOrigin  
          ViewerProtocolPolicy: allow-all 
        DefaultRootObject: index.html   
        Enabled: true
        HttpVersion: 'http2'
        Origins: 
        - DomainName: !Select [2, !Split ["/", !GetAtt MyBucket.WebsiteURL]] 
          Id: KittensOrigin
          CustomOriginConfig: 
            OriginProtocolPolicy: http-only
        PriceClass: PriceClass_All
        ViewerCertificate:  
          AcmCertificateArn: !Ref MyCertificate
          SslSupportMethod: sni-only 
  
  MyRecordName:
    Type: AWS::Route53::RecordSetGroup
    Properties:      
      HostedZoneId: Z08348542LMKDSH94CCW6
      RecordSets:
        - Name: !Ref KittensSubDomainName
          Type: A
          AliasTarget:
            DNSName: !GetAtt MyCloudfront.DomainName
            HostedZoneId: Z2FDTNDATAQYW2

Outputs:
  BucketName: 
    Description: S3 Bucket URL for Kittens Website
    Value: !GetAtt MyBucket.WebsiteURL
  CloudfrontEndpoint:
    Description: Endpoint for Kittens Cloudfront
    Value: !GetAtt MyCloudfront.DomainName
  FullDomainName:
    Description: Full Domain Name of my Application
<<<<<<< HEAD
    Value: !Ref KittensSubDomainName
=======
    Value: !Ref KittensSubDomainName
>>>>>>> 0eea54351547b535f61b474f4890a3d5d04b66e6
